[package]
name = "fileplace-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1"
config = "0.11"
serde = { version = "1", features = ["derive"]}
serde-aux = "3"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
