[package]
name = "fileplace-store"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-cors = "0.6.4"
actix-easy-multipart = "3.0.0"
actix-web = "4"
anyhow = "1"
chrono = "0.4.23"
config = "0.11"
derive_more = "0.99.17"
mime_guess = "2.0.4"
serde = { version = "1", features = ["derive"] }
serde-aux = "3"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.5"
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
urlencoding = "2.1.2"
uuid = { version = "1", features = ["v4"] }
walkdir = "2.3.2"


[dev-dependencies.reqwest]
version = "0.11.14"
default-features = true
features = ["json", "rustls-tls", "cookies", "multipart"]
