[package]
name = "fileplace-store"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-easy-multipart = "3.0.0"
actix-web = "4"
anyhow = "1"
config = "0.11"
mime_guess = "2.0.4"
serde = { version = "1", features = ["derive"] }
serde-aux = "3"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.5"
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
uuid = { version = "1", features = ["v4"] }
